# Settings
backend = "xrender";

# Opacity
## run xprop and then click on a window to find its WM_CLASS(STRING) property
opacity-rule = [
	"90:class_g = 'kitty'",
	"90:class_g = 'firefox-esr'",
	"90:class_g = 'obsidian'",
	"90:class_g = 'Google-chrome'"
];
