#!/usr/bin/env bash

# simple yad gui to show gh commands

Main() {
	source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1

	local command=(

		eos_yad 
		--title="GitHub Commands:" 
		--no-buttons
		--width=500
		--height=400 
		--list

		--column=Command: --column=Description
		"git" "Prefaces every command"
		"status" "Shows state of directory/starging area"
		"log" "Displays commit history of current branch"
		"branch" "Lists the local branches"
		"branch [branch]" "Creates new branch"
		"checkout [branch]" "Switches working directory to [branch]"
		"reset [file]" "Unstages [file]"
		"revert [commit]" "New commit, undoes changes of [commit]"
		"merge [feat-b]" "Merges [feat-b] to the current branch"
		"branch -d [branch]" "Deletes [branch]"
	)

	"${command[@]}"
}

Main "@"
