# See reference at github.com/fairglade/ly//master/res/config.ini
clock = null
animate = true
animation = 1
hide_borders = true
auth_fails = 2
auto_login_session = "hyprland"
bigclock = en
bigclock_12hr = true
lang = en
save = true
