
# i3blocks config file changed for EndeavourOS-i3 setup

# source is available here:
# https://raw.githubusercontent.com/endeavouros-team/endeavouros-i3wm-setup/main/etc/skel/.config/i3/i3blocks.conf
# Maintainer: joekamprad [joekamprad //a_t// endeavouros.com]
# Former Visual Designer: Florent Valetti [@FLVAL EndeavourOS]
# created for i3wm setup on EndeavourOS
# https://endeavouros.com

# cheatsheet for icon fonts used on the block-bar:
# https://fontawesome.com/v4.7/cheatsheet/

# --> to update this run the following command:
# wget --backups=1 https://raw.githubusercontent.com/endeavouros-team/endeavouros-i3wm-setup/main/etc/skel/.config/i3/i3blocks.conf -P ~/.config/i3/

# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks


# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
separator=false
markup=pango

# Date/Time
[date]
command=date '+%a %d %b %H:%M:%S'
interval=1

[spacer]
command=echo " "
interval=once
separator=false
separator_block_width=10

# System Information
[memory]
label= 
command=~/.config/i3/scripts/memory
interval=2

[cpu_usage]
label= 
command=~/.config/i3/scripts/cpu_usage
interval=2

[CPU-temperature]
command=~/.config/i3/scripts/temperature
interval=30

[volume]
command=~/.config/i3/scripts/volume
interval=2

[spacer]
command=echo " "
interval=once
separator=false
seperator_block_width=10

# References
[title]
full_text=References:

[git]
full_text=GitHub
command=~/.config/i3/scripts/gh_ref

[keybindings]
full_text=KeyBindings
command=~/.config/i3/scripts/keyhint

[nvim]
full_text=Nvim
command=~/.config/i3/scripts/nvim_ref

