general {
	gaps_in = 5
	gaps_out = 10
	border_size = 0
	resize_on_border = false
	allow_tearing = false
	layout = dwindle
}

decoration {
	rounding = 0
	active_opacity = 0.8
	inactive_opacity = 0.6
	dim_inactive = true
	dim_strength = 0.1	
	blur {
		enabled = true
		size = 5
		passes = 1
	}
}
