# Set Modkey
$mainMod = SUPER

# Set Variables
$terminal = kitty
 
# Keybindings
bind = $mainMod, Q, killactive
bind = $mainMod, R, exec, bemenu-run --ignorecase --width-factor 1 --scrollbar none --bottom --fn 'BigBlueTerm Nerd Font 12' --no-overlap --hp 4 --tb "##0d1117" --tf "##c9d1d9" --nb "##0d1117" --nf "##c9d1d9" --hb "##58a6ff" --hf "##0d1117"
bind = $mainMod, Return, exec, kitty
bind = $mainMod, L, exit
bind = $mainMod, F, fullscreen, 0

# Switching through workspaces
bind = $mainMod, Tab, workspace, e+1
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window through workspaces
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Move focus
bind = $mainMod, h, movefocus, u
bind = $mainMod, j, movefocus, l
bind = $mainMod, k, movefocus, r
bind = $mainMod, l, movefocus, d

# Volume/brightness controls
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%

# xxx (requires playerctl) 
bindl = , XF86AudionNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play payse
bindl = , XF86AudioPrev, exec, playerctl previous
