#!/usr/bin/env bash

# simple yad gui to show default keybindings

Main() {
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1

    local command=(
        eos_yad 
	--title="EndeavourOS i3-wm keybindings:" 
	--no-buttons 
	--width=500
	--height=400 
	--list

        --column=Key-Combination: --column=Description
        "ESC" "close this app"
        "Win" "modkey" 
        "Win+Enter" "Opens Kitty Terminal" 
        "Win+(0-9)" "Shift Through Workspaces" 
        "Win+n" "Opens New Workspace" 
        "Win+q" "Close Focused App"
	"Win+f" "Fullscreen Focused App"
	"Win+F12" "Screenshot"
	"Win+c" "Opens Clipmenu"
	"Win+l" "Lock Screen Blur" 
        "Win+e" "Logout Menu" 
    )

    "${command[@]}"
}

Main "$@"

